// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteTweetsIDHandlerFunc turns a function with the right signature into a delete tweets ID handler
type DeleteTweetsIDHandlerFunc func(DeleteTweetsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTweetsIDHandlerFunc) Handle(params DeleteTweetsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteTweetsIDHandler interface for that can handle valid delete tweets ID params
type DeleteTweetsIDHandler interface {
	Handle(DeleteTweetsIDParams) middleware.Responder
}

// NewDeleteTweetsID creates a new http.Handler for the delete tweets ID operation
func NewDeleteTweetsID(ctx *middleware.Context, handler DeleteTweetsIDHandler) *DeleteTweetsID {
	return &DeleteTweetsID{Context: ctx, Handler: handler}
}

/*DeleteTweetsID swagger:route DELETE /tweets/{id} deleteTweetsId

Delete tweet

*/
type DeleteTweetsID struct {
	Context *middleware.Context
	Handler DeleteTweetsIDHandler
}

func (o *DeleteTweetsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTweetsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
