// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetTweetsURL generates an URL for the get tweets operation
type GetTweetsURL struct {
	Count     *int64
	FilterTag []string
	Year      *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTweetsURL) WithBasePath(bp string) *GetTweetsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTweetsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetTweetsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/tweets"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var count string
	if o.Count != nil {
		count = swag.FormatInt64(*o.Count)
	}
	if count != "" {
		qs.Set("count", count)
	}

	var filterTagIR []string
	for _, filterTagI := range o.FilterTag {
		filterTagIS := filterTagI
		if filterTagIS != "" {
			filterTagIR = append(filterTagIR, filterTagIS)
		}
	}

	filterTag := swag.JoinByFormat(filterTagIR, "")

	if len(filterTag) > 0 {
		qsv := filterTag[0]
		if qsv != "" {
			qs.Set("filter[tag]", qsv)
		}
	}

	var year string
	if o.Year != nil {
		year = swag.FormatInt64(*o.Year)
	}
	if year != "" {
		qs.Set("year", year)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetTweetsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetTweetsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetTweetsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetTweetsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetTweetsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetTweetsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
