// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pawmart/northerntech-simpletwitter/internal/models"
)

// GetTweetsIDOKCode is the HTTP code returned for type GetTweetsIDOK
const GetTweetsIDOKCode int = 200

/*GetTweetsIDOK Tweet details

swagger:response getTweetsIdOK
*/
type GetTweetsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.TweetDetailsResponse `json:"body,omitempty"`
}

// NewGetTweetsIDOK creates GetTweetsIDOK with default headers values
func NewGetTweetsIDOK() *GetTweetsIDOK {

	return &GetTweetsIDOK{}
}

// WithPayload adds the payload to the get tweets Id o k response
func (o *GetTweetsIDOK) WithPayload(payload *models.TweetDetailsResponse) *GetTweetsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tweets Id o k response
func (o *GetTweetsIDOK) SetPayload(payload *models.TweetDetailsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTweetsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTweetsIDNotFoundCode is the HTTP code returned for type GetTweetsIDNotFound
const GetTweetsIDNotFoundCode int = 404

/*GetTweetsIDNotFound Resource not found

swagger:response getTweetsIdNotFound
*/
type GetTweetsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetTweetsIDNotFound creates GetTweetsIDNotFound with default headers values
func NewGetTweetsIDNotFound() *GetTweetsIDNotFound {

	return &GetTweetsIDNotFound{}
}

// WithPayload adds the payload to the get tweets Id not found response
func (o *GetTweetsIDNotFound) WithPayload(payload *models.APIError) *GetTweetsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tweets Id not found response
func (o *GetTweetsIDNotFound) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTweetsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
