// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchTweetsHandlerFunc turns a function with the right signature into a patch tweets handler
type PatchTweetsHandlerFunc func(PatchTweetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchTweetsHandlerFunc) Handle(params PatchTweetsParams) middleware.Responder {
	return fn(params)
}

// PatchTweetsHandler interface for that can handle valid patch tweets params
type PatchTweetsHandler interface {
	Handle(PatchTweetsParams) middleware.Responder
}

// NewPatchTweets creates a new http.Handler for the patch tweets operation
func NewPatchTweets(ctx *middleware.Context, handler PatchTweetsHandler) *PatchTweets {
	return &PatchTweets{Context: ctx, Handler: handler}
}

/*PatchTweets swagger:route PATCH /tweets patchTweets

Patch tweet

*/
type PatchTweets struct {
	Context *middleware.Context
	Handler PatchTweetsHandler
}

func (o *PatchTweets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchTweetsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
