// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostTweetsHandlerFunc turns a function with the right signature into a post tweets handler
type PostTweetsHandlerFunc func(PostTweetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTweetsHandlerFunc) Handle(params PostTweetsParams) middleware.Responder {
	return fn(params)
}

// PostTweetsHandler interface for that can handle valid post tweets params
type PostTweetsHandler interface {
	Handle(PostTweetsParams) middleware.Responder
}

// NewPostTweets creates a new http.Handler for the post tweets operation
func NewPostTweets(ctx *middleware.Context, handler PostTweetsHandler) *PostTweets {
	return &PostTweets{Context: ctx, Handler: handler}
}

/*PostTweets swagger:route POST /tweets postTweets

Create tweet

*/
type PostTweets struct {
	Context *middleware.Context
	Handler PostTweetsHandler
}

func (o *PostTweets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostTweetsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
