// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Northern Tech Simple Twitter App - Pawel Martuszewski

    Schemes:
      http
    Host: localhost:6543
    BasePath: /v1
    Version: 1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
