// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/vnd.api+json",
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Northern Tech Simple Twitter App - Pawel Martuszewski",
    "version": "1"
  },
  "host": "localhost:6543",
  "basePath": "/v1",
  "paths": {
    "/health": {
      "get": {
        "summary": "Fetch service health",
        "responses": {
          "200": {
            "description": "Service health",
            "schema": {
              "$ref": "#/definitions/Health"
            }
          }
        }
      }
    },
    "/tweets": {
      "get": {
        "summary": "List tweets",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string",
              "format": "string"
            },
            "description": "Filter by tag",
            "name": "filter[tag]",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "Count",
            "name": "count",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "Year",
            "name": "year",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of tweet details",
            "schema": {
              "$ref": "#/definitions/TweetDetailsListResponse"
            }
          },
          "500": {
            "description": "Fatal error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/vnd.api+json",
          "application/json"
        ],
        "summary": "Create tweet",
        "parameters": [
          {
            "name": "Tweet creation request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/TweetCreation"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Tweet creation response",
            "schema": {
              "$ref": "#/definitions/TweetCreationResponse"
            }
          },
          "400": {
            "description": "Tweet creation error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          },
          "500": {
            "description": "Fatal error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/vnd.api+json",
          "application/json"
        ],
        "summary": "Patch tweet",
        "parameters": [
          {
            "name": "Tweet update request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/TweetUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Tweet update response"
          },
          "400": {
            "description": "Tweet update error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          },
          "404": {
            "description": "Tweet update not found",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          },
          "500": {
            "description": "Fatal error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    },
    "/tweets/{id}": {
      "get": {
        "summary": "Fetch tweet",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Tweet Id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Tweet details",
            "schema": {
              "$ref": "#/definitions/TweetDetailsResponse"
            }
          },
          "404": {
            "description": "Resource not found",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/vnd.api+json",
          "application/json"
        ],
        "summary": "Delete tweet",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Tweet Id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Tweet deletion response"
          },
          "404": {
            "description": "Tweet deletion error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiError": {
      "type": "object",
      "properties": {
        "error_code": {
          "type": "string"
        },
        "error_message": {
          "type": "string"
        }
      }
    },
    "Health": {
      "type": "object",
      "properties": {
        "status": {
          "description": "Status of the service. Can either be ` + "`" + `up` + "`" + ` or ` + "`" + `down` + "`" + `.",
          "type": "string",
          "enum": [
            "up",
            "down"
          ],
          "example": "up"
        }
      }
    },
    "Links": {
      "type": "object",
      "properties": {
        "first": {
          "description": "Link to the first resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "last": {
          "description": "Link to the last resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "next": {
          "description": "Link to the next resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "prev": {
          "description": "Link to the previous resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "self": {
          "description": "Link to this resource type",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        }
      }
    },
    "Tweet": {
      "type": "object",
      "required": [
        "tag",
        "attributes"
      ],
      "properties": {
        "attributes": {
          "type": "object",
          "required": [
            "message"
          ],
          "properties": {
            "message": {
              "description": "Tweet message",
              "type": "string",
              "pattern": "^[A-Z a-z_]*$",
              "example": "hello John"
            },
            "user_id": {
              "description": "Unique ID of the user this resource is created by",
              "type": "string",
              "pattern": "^[[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}$",
              "example": "ee2fb143-6dfe-4787-b183-ca8ddd4164d2"
            }
          }
        },
        "created_on": {
          "type": "integer",
          "x-nullable": true
        },
        "id": {
          "description": "Unique resource ID",
          "type": "string",
          "pattern": "^[[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}$",
          "example": "7826c3cb-d6fd-41d0-b187-dc23ba928772"
        },
        "modified_on": {
          "type": "integer",
          "x-nullable": true
        },
        "tag": {
          "description": "Name of the resource tag",
          "type": "string",
          "pattern": "^[A-Z a-z_]*$",
          "example": "text"
        }
      }
    },
    "TweetCreation": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        }
      }
    },
    "TweetCreationResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        },
        "links": {
          "$ref": "#/definitions/Links"
        }
      }
    },
    "TweetDetailsListResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tweet"
          }
        },
        "links": {
          "$ref": "#/definitions/Links"
        }
      }
    },
    "TweetDetailsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        },
        "links": {
          "$ref": "#/definitions/Links"
        }
      }
    },
    "TweetUpdate": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/vnd.api+json",
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Northern Tech Simple Twitter App - Pawel Martuszewski",
    "version": "1"
  },
  "host": "localhost:6543",
  "basePath": "/v1",
  "paths": {
    "/health": {
      "get": {
        "summary": "Fetch service health",
        "responses": {
          "200": {
            "description": "Service health",
            "schema": {
              "$ref": "#/definitions/Health"
            }
          }
        }
      }
    },
    "/tweets": {
      "get": {
        "summary": "List tweets",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string",
              "format": "string"
            },
            "description": "Filter by tag",
            "name": "filter[tag]",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "Count",
            "name": "count",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "Year",
            "name": "year",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of tweet details",
            "schema": {
              "$ref": "#/definitions/TweetDetailsListResponse"
            }
          },
          "500": {
            "description": "Fatal error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/vnd.api+json",
          "application/json"
        ],
        "summary": "Create tweet",
        "parameters": [
          {
            "name": "Tweet creation request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/TweetCreation"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Tweet creation response",
            "schema": {
              "$ref": "#/definitions/TweetCreationResponse"
            }
          },
          "400": {
            "description": "Tweet creation error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          },
          "500": {
            "description": "Fatal error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/vnd.api+json",
          "application/json"
        ],
        "summary": "Patch tweet",
        "parameters": [
          {
            "name": "Tweet update request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/TweetUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Tweet update response"
          },
          "400": {
            "description": "Tweet update error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          },
          "404": {
            "description": "Tweet update not found",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          },
          "500": {
            "description": "Fatal error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    },
    "/tweets/{id}": {
      "get": {
        "summary": "Fetch tweet",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Tweet Id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Tweet details",
            "schema": {
              "$ref": "#/definitions/TweetDetailsResponse"
            }
          },
          "404": {
            "description": "Resource not found",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/vnd.api+json",
          "application/json"
        ],
        "summary": "Delete tweet",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Tweet Id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Tweet deletion response"
          },
          "404": {
            "description": "Tweet deletion error",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiError": {
      "type": "object",
      "properties": {
        "error_code": {
          "type": "string"
        },
        "error_message": {
          "type": "string"
        }
      }
    },
    "Health": {
      "type": "object",
      "properties": {
        "status": {
          "description": "Status of the service. Can either be ` + "`" + `up` + "`" + ` or ` + "`" + `down` + "`" + `.",
          "type": "string",
          "enum": [
            "up",
            "down"
          ],
          "example": "up"
        }
      }
    },
    "Links": {
      "type": "object",
      "properties": {
        "first": {
          "description": "Link to the first resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "last": {
          "description": "Link to the last resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "next": {
          "description": "Link to the next resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "prev": {
          "description": "Link to the previous resource in the list",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        },
        "self": {
          "description": "Link to this resource type",
          "type": "string",
          "example": "http://localhost:6543/v1/api_name/resource_tag"
        }
      }
    },
    "Tweet": {
      "type": "object",
      "required": [
        "tag",
        "attributes"
      ],
      "properties": {
        "attributes": {
          "type": "object",
          "required": [
            "message"
          ],
          "properties": {
            "message": {
              "description": "Tweet message",
              "type": "string",
              "pattern": "^[A-Z a-z_]*$",
              "example": "hello John"
            },
            "user_id": {
              "description": "Unique ID of the user this resource is created by",
              "type": "string",
              "pattern": "^[[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}$",
              "example": "ee2fb143-6dfe-4787-b183-ca8ddd4164d2"
            }
          }
        },
        "created_on": {
          "type": "integer",
          "x-nullable": true
        },
        "id": {
          "description": "Unique resource ID",
          "type": "string",
          "pattern": "^[[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}$",
          "example": "7826c3cb-d6fd-41d0-b187-dc23ba928772"
        },
        "modified_on": {
          "type": "integer",
          "x-nullable": true
        },
        "tag": {
          "description": "Name of the resource tag",
          "type": "string",
          "pattern": "^[A-Z a-z_]*$",
          "example": "text"
        }
      }
    },
    "TweetCreation": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        }
      }
    },
    "TweetCreationResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        },
        "links": {
          "$ref": "#/definitions/Links"
        }
      }
    },
    "TweetDetailsListResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tweet"
          }
        },
        "links": {
          "$ref": "#/definitions/Links"
        }
      }
    },
    "TweetDetailsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        },
        "links": {
          "$ref": "#/definitions/Links"
        }
      }
    },
    "TweetUpdate": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Tweet"
        }
      }
    }
  }
}`))
}
